[package]
name = "drone"
version = "0.1.0"
edition = "2021"

[dependencies]
network = { path = "../network" }
packet = { path = "../packet" }
controller = { path = "../controller" }
crossbeam-channel = "0.5.13"
